name: Test workflow
on: [push]
jobs:
  run:    
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:      
        operating-system: [macos-latest]
        php: [7.4]
        #php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    name: Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - run: |
        sed -i '' "s/ keg.link(verbose: verbose?)/ keg.link(verbose: verbose?, overwrite: true)/" "$(brew --repository)"/Library/Homebrew/formula_installer.rb
        trap 'git -C "$(brew --repository)" stash' EXIT
        git -C "$(brew --repository)" diff
    
    - run: git -C "$(brew --repository)" diff    
     
    - name: Setup PHP
      uses: shivammathur/setup-php@verbose  
      with:
        php-version: ${{ matrix.php }}
      env:
        update: true
    - name: Test PHP
      run: |
        php -v && php -m
    - name: Test PHP service
      run: |
        brew services start php@${{ matrix.php }}
        brew services list
        formula='php@${{ matrix.php }}'
        [ "$formula" = "php@8.0" ] && formula='php'
        cat ~/Library/LaunchAgents/homebrew.mxcl."$formula".plist
