name: Test workflow #test1
on: [push]
jobs:
  run:    
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:      
        operating-system: [macos-10.15]
        php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    name: Test macOS
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - run: brew update

    - name: Setup PHP
      uses: shivammathur/setup-php@verbose
      with:
        php-version: ${{ matrix.php }}

    - name: Test PHP version
      run: |
        php -v
      
    - name: Test PHP extensions
      run: php -m
