name: Test workflow #test darwin
on: [push]
jobs:
  old_versions:
    name: darwin
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest]
        php-versions: ['7.2', '7.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        run: |
          brew tap shivammathur/homebrew-php
          brew install shivammathur/php@${{ matrix.php-versions }}
          brew link --force --overwrite php@${{ matrix.php-versions }}
      
      - name: Test PHP version
        run: php -v && php -m
