name: Test workflow #test darwin
on: [push]
jobs:
  old_versions:
    name: darwin
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest]        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          sudo mkdir Formula
          PHP_VERSION=php
          curl -o Formula/php.rb -SL https://raw.githubusercontent.com/shivammathur/homebrew-php/master/Formula/$PHP_VERSION.rb
          sed -i '' 's/\s\sdepends_on "jpeg".*/  depends_on "jpeg"\n  depends_on "krb5"/g' "Formula/$PHP_VERSION.rb"
          cat "Formula/$PHP_VERSION.rb"
