name: Phalcon workflow
on: [push]
jobs:
  phalcon3:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-16.04, windows-latest, macos-latest]
        php-versions: ['7.0', '7.1', '7.2', '7.3']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@develop
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: phalcon3

      - name: Testing PHP version
        run: php -v

      - name: Testing Extensions
        run: |
          php -r 'var_dump(new class(new Phalcon\Di\FactoryDefault) extends Phalcon\Mvc\Model {});'
          php -r "echo 'phalcon: ' . phpversion('phalcon');"
          php -r "if(! extension_loaded('phalcon')) {throw new Exception('phalcon not found');}"
          php -r "if(phpversion('phalcon')[0]!='3') {throw new Exception('Wrong phalcon version Installed');}"

  phalcon4:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-16.04, windows-latest, macos-latest]
        php-versions: ['7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@develop
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: phalcon4

      - name: Testing PHP version
        run: php -v

      - name: Testing Extensions
        run: |
          php -r 'var_dump(new class(new Phalcon\Di\FactoryDefault) extends Phalcon\Mvc\Model {});'
          php -r "echo 'psr: ' . phpversion('psr').', ';"
          php -r "echo 'phalcon: ' . phpversion('phalcon');"
          php -r "if(! extension_loaded('psr')) {throw new Exception('psr not found');}"
          php -r "if(! extension_loaded('phalcon')) {throw new Exception('phalcon not found');}"
          php -r "if(phpversion('phalcon')[0]!='4') {throw new Exception('Wrong phalcon version Installed');}"